### ISSUE TITLE
ICE connectivity problem

### ISSUE THREAD

**Issue by enobufs** [pion/ice#13]
### Your environment.
  - Version: v2.0.3
  - Browser: n/a

### What did you do?
I am experiencing a connectivity problem (ICE) between two nodes (using v2.0.3). Both ends are behind different NATs which happened to be the same type, port-restricted cone NAT.
### What did you expect?
ICE connection state (both ends) should go to "connected"

### What happened?
One end's ICE connection state is stuck with "checking" forever. The other end went to "connected".  Data channel I am trying to open wouldn't open.

**Comment by enobufs** [comment]
[ice-connection-issue.pcapng.zip](https://github.com/pion/ice/files/3066239/ice-connection-issue.pcapng.zip)
[answerer.log](https://github.com/pion/ice/files/3066241/answerer.log)
[offerer.log](https://github.com/pion/ice/files/3066242/offerer.log)

pcap file (zipped) and offerer and answerer logs are attached.

The pcap is done at the offerer's network (behind a NAT).
Funny thing is, the pcap indicates a STUN request packet going out and its response is coming back. But offerer's log does not indicate anything about successful connectivity checking.

I have a theory from my observation:
* Current implementation reacts only to the *incoming STUN request*
* Receipt of STUN response wouldn't be useful because current implementation does not generate another SDP to inform the successful connectivity check result to the peer.

Here's "I believe" what's happening:
1. Answerer sends a ping to Offerer (will be dropped by peer's NAT as not "hole-punched" yet
2. Offerer sends a ping to Answerer. It will reach the answerer, moves the state to "connected"
3. As answerer never sends the ping again (you can see with the log), it will be stuck at "checking" state.

If the above theory is correct, then the cause is the answerer not keep sending the ping to the offerer until it sees a STUN response is successfully coming back.

What I don't know about:
* If ICE spec says connectivity checking is considered as successful when:
    - STUN request is received
    - STUN response is received
We should check the spec.

**Comment by maxhawkins** [comment]
```
7.1.3.2.  Success Cases

   A check is considered to be a success if all of the following are
   true:

   o  The STUN transaction generated a success response.

   o  The source IP address and port of the response equals the
      destination IP address and port to which the Binding request was
      sent.

   o  The destination IP address and port of the response match the
      source IP address and port from which the Binding request was
      sent.
```

Going to try to find where this is implemented in the code...

**Comment by enobufs** [comment]
@maxhawkins I added the logging as you requested.
```
diff --git a/candidate.go b/candidate.go
index 8f0cc4c..0ca74ad 100644
--- a/candidate.go
+++ b/candidate.go
@@ -140,7 +140,10 @@ func (c *Candidate) recvLoop() {
                        return
                }

+               log.Debugf("candidate received %d bytes of data", n)
+
                if stun.IsSTUN(buffer[:n]) {
+                       log.Debug("is STUN")
                        var m *stun.Message
                        m, err = stun.NewMessage(buffer[:n])
                        if err != nil {
@@ -156,6 +159,7 @@ func (c *Candidate) recvLoop() {

                        continue
                } else {
+                       log.Debug("is NOT STUN")
                        err = c.agent.run(func(agent *Agent) {
                                agent.noSTUNSeen(c, srcAddr)
                        })
```
But it does not show up on the console ....
If I put both nodes in the local network, the same binary, I can see the logs...

**Comment by enobufs** [comment]
I believe the problem is in my environment… The node that does not receive STUN packets are under mobile hotspot network via my Android…  I found another port-restrict NAT environment, pion successfully established a connection through the port-restricted NATs on both ends.

**Comment by enobufs** [comment]
@maxhawkins @Sean-Der
Additional note.  Mobile hotspot is ruled out.  It happens with a standard WiFi via Comcast also.

I also double-checked a new pcap that the STUN (connectivity check) response is definitely coming back from the remote candidate, but nothing is from ReadFrom().

It's almost like we have net.PacketConn suddenly turned into a `connected UDP socket`. (only receives from / sends to) a specific remote addr...  But I checked, the c.conn.(*net.UDPConn).RemoteAddr() returns nil...   So, still no clue... (are we stumbling on some net package glitch?)

```
$ go version
go version go1.12.1 darwin/amd64
```

I flipped offerer and answerer. (between MBP and Ubuntu).  Now, answerer isn't receiving packets... (MBP is always is the one that has the problem).

**Comment by Sean-Der** [comment]
Nice digging @enobufs 

So UDP traffic is arriving on a host+port that is listening, but ReadFrom isn't returning anything?

**Comment by Sean-Der** [comment]
I don't like this https://github.com/pion/ice/blob/master/candidate.go#L139 we should probably do something with this error (could it be this?)

**Comment by enobufs** [comment]
I added a debug log in the error case also, but nothing printed.  I guess it is stuck inside ReadFrom()...

**Comment by Sean-Der** [comment]
@enobufs If you send something to that host+port that the candidate is listening on with `netcat` does the ReadFrom pass/work?

**Comment by enobufs** [comment]
I feel so dumb...  My mac had firewall enabled (ESET).  When I turn it off, the problem goes away...  @maxhawkins, how about your mac?

**Comment by maxhawkins** [comment]
Mine was a [completely unrelated SDP issue](https://github.com/pion/webrtc/issues/616). I wrote the bug myself a couple days ago. 🤦‍♂️

**Comment by enobufs** [comment]
Okay!  Let me close this issue.
