### ISSUE TITLE
Candidate.Priority() is completely wrong

### ISSUE THREAD

**Issue by kixelated** [pion/ice#14]
https://github.com/pion/ice/blob/7245ac0866456f7c39a534f496d0f346ab7aad30/candidate.go#L212

`^` is XOR in Go, not exponentiation. `2^24 == 26`.

It should be `(1<<24) * c.Type().Preference()` or simply `c.Type().Preference() << 24`.

`uint16` is also not large enough to hold the correct value.

**Comment by kixelated** [comment]
Also: https://github.com/pion/ice/blob/7245ac0866456f7c39a534f496d0f346ab7aad30/candidatepair.go#L76

**Comment by maxhawkins** [comment]
@mjmac I think this might be related to my issue so I'm working on a PR
