### ISSUE TITLE
ICE username mismatch

### ISSUE THREAD

**Issue by backkem** [pion/ice#152]
Looks like there may be an issue with ICE username. I get an ICE warning indicating the username is concatenated with another string:
```
ice WARNING: 2020/01/06 20:58:20 discard message from (host 192.168.0.238:51718), unknown TransactionID 0xad67559870175f62fa4e89b5
ice WARNING: 2020/01/06 20:58:20 discard message from (192.168.0.238:51795), username mismatch expected(734f496d566d7652436e4872705943433a) actual(734f496d566d7652436e4872705943433a6564625675634b515a6e757a69564e4b)
ice WARNING: 2020/01/06 20:58:20 discard message from (192.168.56.1:51796), username mismatch expected(734f496d566d7652436e4872705943433a) actual(734f496d566d7652436e4872705943433a6564625675634b515a6e757a69564e4b)
```

May be a clue: The particular test starts 50 parallel peer connections. Not sure if this use-case is covered by the Pion test-suite.

### Your environment.
  - Version: 726a16faa60dccdc8c00df8e1ae6426bf5b3bd05
  - Browser: N/A
  - OS: Windows

### What did you do?
I updated [libp2p/go-libp2p-webrtc-direct](https://github.com/libp2p/go-libp2p-webrtc-direct) to latest pion/webrtc (726a16faa60dccdc8c00df8e1ae6426bf5b3bd05) and ran the test-suite with the race detector activated: `go test -v -race -count=1 .`
Note that the test doesn't fail it just takes a longer time due to this issue.

**Comment by Sean-Der** [comment]
@backkem closing for now, but please re-open if you disagree! We can add more log messages, but might make the code less terse.

**Comment by backkem** [comment]
This still persists. CI run with logging: https://travis-ci.org/libp2p/go-libp2p-webrtc-direct/builds/660314127. Seems like this may also be related to https://github.com/pion/webrtc/issues/651#issuecomment-487831188.

Sadly I don't have the bandwidth to dive deeper ATM.

**Comment by Sean-Der** [comment]
https://github.com/pion/ice/issues/152#issuecomment-579643129 what do you think of this comment earlier?

I can add a log message, but I would expect this to happen. During signaling one side has candidates + remote creds (and doesn't know if the other side is ready yet)

**Comment by Sean-Der** [comment]
Hey @backkem sorry closing again :(

Happy to talk about this in Slack, but I am pretty sure this isn't an issue (we are just printing a message we didn't before)
