### ISSUE TITLE
TCP Support?

### ISSUE THREAD

**Issue by Ambyjkl** [pion/ice#196]
## Summary

https://github.com/pion/webrtc/blob/bd6c5cbc71fc401eac3cd158c97586a79f92d34e/networktype.go#L13

TCP is not yet supported.

## Motivation

Feature completeness and spec compliance.

**Comment by Ambyjkl** [comment]
Hi Sean,
Thanks for the info, I'll definitely look into TURN, since that would really help users struggling with UDP. I won't call this a blocker yet, but it would still be great to have eventually. Keep up the good work :+1:

**Comment by Sean-Der** [comment]
@Ambyjkl 

100% agree. I need to get Simulcast done first, but after that I can implement this! I actually will not be that hard either (maybe a 3 days of work at most)

I would run a TURN server in the short term, and then have your users use it! It will act as a 'TCP to UDP proxy' so they can send/receive UDP traffic over TCP.

Thanks for using Pion, always excited to hear people are building stuff with it.

**Comment by Sean-Der** [comment]
Also if you are interested in contributing would love to help you work on this (totally understand if not)

I am always looking to get more people involved :)

**Comment by Ambyjkl** [comment]
@Sean-Der

Sorry for the late reply, TURN is getting the job done for now, kinda. Users report poor experience when using TURN, which is a little strange as we are using pion just for the datachannel and there isn't a lot of data being sent over the wire, and the TURN server is running on the same instance. Initially, we used pion/turn but faced connection drop issues (will make an issue on github for that). We switched to coturn, and that seems to be more stable. Perhaps native TCP would be better.

I don't have the time to contribute right now, unfortunately. If you are too swamped to do this yourself, I can maybe find a friend who might be interested.

**Comment by Sean-Der** [comment]
@Ambyjkl I agree Native TCP would be a lot better!.You are paying a lot of extra costs with TURN (CPU and network)

If you are able to find someone to contribute that would be amazing! I think I could work on this in the next month or so though.
