### ISSUE TITLE
Valid peers can create Prflx candidates for addresses they don't control 

### ISSUE THREAD

**Issue by kixelated** [pion/ice#21]
1. Attacker sends a BindRequest to Pions and gets saved as a validPair.
2. Attacker never replies to Pion's BindRequest messages (so it will stay a validPair not selectedPair).
3. Attacker/Pions performs DTLS handshake.
4. Attacker sends a BindRequest with a higher priority and a spoofed return address (the target), which is also saved as a validPair.
5. Pions now proceeds to send raw SRTP/data to the target address.
6. Attacker can send RTCP/keep-alive information to keep the connection open.

This allows an attacker to DDoS a target without sending the data itself.

The fix involves requiring a SuccessResponse from a CandidatePair before writing to it. This may go against what the ICE RFC requires. It might actually not be possible because of NAT stuff, which is potentially a huge issue.

**Comment by Sean-Der** [comment]
Hey @kixelated 

I don't think this is possible anymore, BindRequests are filtered via MessageIntegrity (so if the attacker doesn't know the pwd we are safe)

**Comment by kixelated** [comment]
Nope, not safe. The attacker in this case will set up a PeerConnection using it's own credentials. It can set up ICE/DTLS/SRTP everything. Except it will suddenly claim to have a different IP address by forging the UDP return address header. This tricks the server to take the attacker's legitimate PeerConnection and redirect it elsewhere.

For example, if Pions gets a STUN binding request that claims to be sent from `google.com:80`, it will mark it as a `validPair` and potentially use it as the result from `getBestPair`. Pions would then proceed to shove SRTP/DTLS traffic at Google which won't know what to do with it. The PeerConnection can be kept alive by the attacker because they can still send RTCP/STUN packets from their valid but lower priority real IP address.

**Comment by Sean-Der** [comment]
`if Pions gets a STUN binding request that claims to be sent from google.com:80`

How? Binding requests are discarded unless you know the uPwd

**Comment by Sean-Der** [comment]
Talked to @kixelated on Slack I understand the issue now.

----

We have to check TransactionIDs and we MUST require success responses from peers. Otherwise a candidate could give us invalid prflx candidates (and we would start sending traffic to 3rd parties unexpectedly)
