### ISSUE TITLE
Conn can be null in candidate_base.go

### ISSUE THREAD

**Issue by mv-s1** [pion/ice#247]
There is no check for null value - c.conn can be null
https://github.com/pion/ice/blob/12f44e93f1857fba92a6ed07e2dc416ba2f8e3f6/candidate_base.go#L203

> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x12e19ce]

>goroutine 41 [running]:
>github.com/pion/ice/v2.(*candidateBase).writeTo(0xc00020a0b0, 0xc0003c0000, 0x70, 0x80, 0x1586e00, 0xc0001370e0, 0x0, 0x0, 0x0)
	/Users/mac/Dev/pkg/mod/github.com/pion/ice/v2@v2.0.0-rc.6/candidate_base.go:203 +0x4e

**Comment by Sean-Der** [comment]
Thanks for the report @mv-s1 !

Did you hit this by doing an ICE Restart? If you have a reproduce or test I can work on fixing this.

thanks!

**Comment by mv-s1** [comment]
Yes, i hit this right after ICE Restarts. 
I fix this by just adding "if c.conn != nil {" :)

**Comment by Sean-Der** [comment]
@mv-s1 If you have a chance opening a PR would be really appreciated :)

I am worried this might be a race condition though, but tests will catch that for us! 

thanks

**Comment by Sean-Der** [comment]
@mv-s1 would you mind trying out master and see if it fixes your issue? If it does will tag a new release, thanks!

**Comment by mv-s1** [comment]
Everything is fine! Thanks!
