### ISSUE TITLE
testing: add integration testing that asserts STUN/NAT hole punching is working properly

### ISSUE THREAD

**Issue by backkem** [pion/ice#27]
Investigate ways to simulate and test traversal of different NAT types and combinations of NAT types.

Related:

- libp2p/go-libp2p#111

**Comment by Sean-Der** [comment]
@enobufs you ok with me closing this as a `dupe` of your vnet work? I think everything will be covered when that rolls out.

We can simulate all NAT types between peers (and that we get the expected behavior) so I think that covers everything!

**Comment by enobufs** [comment]
Yes, I'd agree. Let me close this issue.
Related: pion/webrtc#712
