### ISSUE TITLE
Implement regular nomination

### ISSUE THREAD

**Issue by Sean-Der** [pion/ice#28]
We need to stop using aggressive nomination. 

If we have multiple pairs this can cause us to have different choices on each side (since the last pair with `use-candidate` is chosen. 

Right now we just send every pair a 'USE-CANDIDATE' this means that each side may choose different candidates, all depending on when packets arrive.

Also then if you choose different candidates they will eventually die. ICE only does ping via SendIndications and we have no pongs. So each side is just sending pings and eventually each side dies since they haven't gotten any inbound traffic in 30 seconds.

**Comment by Sean-Der** [comment]
@backkem @enobufs @hugoArregui 

Does this sound right ^ with this I am not sure how aggressive nomination every properly works. It seems very easy for pairs to flake if you have multiple.

**Comment by enobufs** [comment]
@Sean-Der It Sounds right to me! (poorly implemented agent may get confused or trigger a bug if it sees nominated candidate changing so frequently...)

**Comment by hugoArregui** [comment]
It sounds right to me too!
