### ISSUE TITLE
Breaking change in patch release (2.1.10 -> 2.1.11)

### ISSUE THREAD

**Issue by jawnsy** [pion/ice#385]
Hey there!

The most recent patch release included a breaking change to the API, due to removal of the previously-exported `Unknown` symbol. Considering that this was a patch release, that was... unexpected. :sweat_smile: 

The problematic change appears to be https://github.com/pion/ice/commit/366757d59dd224ef8d8cec428bc343c8c16c8bed

I would have expected some sort of deprecation period prior to removal, as well as a notification in release notes or similar. It's not a big deal for us to change things over, just wanted to let you know!

We discovered this when Dependabot opened a PR to update this library: https://github.com/cdr/coder-cli/pull/413

It might be better to change NewSchemeType so that it can return an error for unknown schemes, which would also simplify the following code, but that's also a breaking change to the API: https://github.com/pion/ice/blob/7ccaaacf393a384db11d4b99c32f9dcec4431d49/url.go#L120-L123

For example, if we had:

```go
// NewSchemeType defines a procedure for creating a new SchemeType from a raw
// string naming the scheme type.
func NewSchemeType(raw string) (SchemeType, error) {
	switch raw {
	case "stun":
		return SchemeTypeSTUN, nil
	case "stuns":
		return SchemeTypeSTUNS, nil
	case "turn":
		return SchemeTypeTURN, nil
	case "turns":
		return SchemeTypeTURNS, nil
	default:
		return nil, ErrUnknownScheme
	}
}
```

then the ParseURL code could do something like:

```go
	u.Scheme, err = NewSchemeType(rawParts.Scheme)
	if err != nil {
		return nil, err // maybe wrapping the error?
	}
```

**Comment by Sean-Der** [comment]
Oops that is my mistake! I will revert new and tag a new patch release

**Comment by Sean-Der** [comment]
Thank you so much for opening this issue. Will also improve `NewSchemeType` since we have the chance.

Thinking about it more I think we can do better then `Unknown` enum as well. It seems more idiomatic to do `iota + 1` and use a switch to detect an invalid value?

**Comment by jawnsy** [comment]
Thanks for the quick reply on this!
