### ISSUE TITLE
How to create a TCP connection with pion/ice

### ISSUE THREAD

**Issue by liyoubdu** [pion/ice#393]
i run pion\ice\examples\ping-pong\main.go, it work well.

then i modify main.go, change udp4 to tcp4:
`	iceAgent, err = ice.NewAgent(&ice.AgentConfig{`
	`	NetworkTypes: []ice.NetworkType{ice.NetworkTypeTCP4},  //<---here`
	`})`

try again. but it can not work well.
so, what should i do?

**Comment by stv0g** [comment]
Please try to reach out to our Slack channel for support.
This is not the correct place for asking questions.
