### ISSUE TITLE
Allow ICE to open sockets listening on the loopback interface

### ISSUE THREAD

**Issue by nerthazrim** [pion/ice#494]
## Summary

Allow (and force?) ICE to open sockets listening on the loopback interface.
This can be useful when lo is carrying the IP address one would want to expose.

## Motivation

My VPS host configures its VMs to have their public IPs on the loopback interface.
Therefore, when using Livekit Server, I have to set up DNAT in order to NAT incoming packets on the public IP to the private IP, on which ICE opens a socket.
It would be nice to be able to force ICE to listen on the loopback interface, in my case exposing the public IP.

## Describe alternatives you've considered

DNAT as stated above :)

## Additional context

Initial discussion here, on the Livekit Server project: https://github.com/livekit/livekit/issues/1160

Thanks in advance!

**Comment by Sean-Der** [comment]
@cnderrauber I wonder if we could/should have some heuristic to auto enable this also?

Would it help (or hurt) users if we saw they had zero interfaces enable loopback?

**Comment by cnderrauber** [comment]
@Sean-Der I am concerned that users might be confused by candidates containing loopback addresses if we enable it automatically, since in most case we don't need loopback addresses.
I'm not sure if enable it when no interfaces found will help user, but for this case, the VM have two interfaces, but only the loopback one can be accessed by public clients.

**Comment by nerthazrim** [comment]
Hi @cnderrauber,

I believe you have a parameter forcing ICE to listen on a specific interface.
As far as I know, this parameter does not allow "lo" as value.

Would it be possible to allow it?
It would solve my problem and won't have any impact on more "standard", let's say, network setups.
