### ISSUE TITLE
Connection upgrade

### ISSUE THREAD

**Issue by stv0g** [pion/ice#543]
Does pion/ice support switching a connection to better candidates once they become available?

With better, I mean candidate pairs with a higher priority? E.g. switching from relay candidates back to host candidates?

**Comment by Sean-Der** [comment]
Hey @stv0g 

You will have to do this manually with a [ICE Restart](https://pkg.go.dev/github.com/pion/ice/v2#Agent.Restart)

Auto switching back and forth is not something the protocol itself supports. There was some discussion in the IETF [here](https://datatracker.ietf.org/meeting/111/materials/slides-111-dispatch-nicer-nicer-ice-based-on-rtt-00.pdf) not sure where it went.

**Comment by Sean-Der** [comment]
You should email Jonas Oreland, Harald Alvestrand and ask about it!

**Comment by stv0g** [comment]
Thanks for the clarification Sean :) I will close the issue then :)
