### ISSUE TITLE
Rename Agent.startOnConnectionStateChangeRoutine() to Agent.startRoutines()

### ISSUE THREAD

**Issue by stv0g** [pion/ice#556]
Currently the method appears to be doing more than starting the `OnConnectionStateChange` routine.
I propose to rename the method to `startRoutines()`:

https://github.com/pion/ice/blob/5ef81b65f45a6c05f3553385d4b40e32b0601243/agent.go#L422

**Comment by Sean-Der** [comment]
@stv0g :+1: sounds good to me!

Please modify/refactor any APIs that aren't public whenever you think makes sense :)
