### ISSUE TITLE
Support server reflexive TCP candidate type

### ISSUE THREAD

**Issue by joshua-kim** [pion/ice#569]
### Your environment.
  - Version: *Release or SHA* 1d502ca6ec1075a762339556a5734e4b4441c452
  - Browser: *include version* N/A
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

[diff.txt](https://github.com/pion/ice/files/11491159/diff.txt) <- diff to apply to get the test case I made

Trying to modify the unit test that tests active TCP to set up an example of two agents connecting over TCP through a TURN server but it results in no candidates being generated so they can't connect:
```
=== RUN   TestAgentActiveTCP/STUN_server
passive-ice-tcp-mux INFO: 2023/05/17 04:04:22 Listening TCP on 192.168.0.104:7686
ice TRACE: 04:04:22.314904 agent.go:512: Unset selected candidate pair
ice TRACE: 04:04:22.315450 agent.go:512: Unset selected candidate pair
ice DEBUG: 04:04:22.315595 agent.go:394: Started agent: isControlling? true, remoteUfrag: "TWLVUTobKdxWWteA", remotePwd: "zqPmOQQoFzlYOeSnVMoEeBrlwOvdjYwD"
ice INFO: 2023/05/17 04:04:22 Setting new connection state: Checking
ice DEBUG: 04:04:22.315613 agent.go:394: Started agent: isControlling? false, remoteUfrag: "ZpxkYwxnfOjTAnoA", remotePwd: "NCZUyLJpmyWfDwtLvJpyhAMPhFoNlMcA"
ice INFO: 2023/05/17 04:04:22 Setting new connection state: Checking
ice TRACE: 04:04:22.315643 agent.go:535: pinging all candidates
ice WARNING: 2023/05/17 04:04:22 Failed to ping without candidate pairs. Connection is not possible yet.
ice TRACE: 04:04:22.315653 agent.go:535: pinging all candidates
```

### What did you do?
I'm trying to see if it's possible to set up ICE over TCP to connect two nodes over a STUN server. I'm pretty new to how ICE works but I believe this should be possible since active-tcp support just got merged in?

### What did you expect?
Would expect to be able to connect two ice agents via a stun server

### What happened?
Test fails

**Comment by stv0g** [comment]
@ashellunts I think this might interest you.

**Comment by ashellunts** [comment]
Hi @joshua-kim,

server reflexive TCP candidates are not supported. Only host ones.

Can you describe what is your use case? Can NAT1To1IPs help you?

**Comment by stv0g** [comment]
> Server reflexive TCP candidates are not supported. Only host ones.

Just wondering, is this even possible/reasonable to implement support for Active/Passive TCP types?
Or is the SimultaneousOpen TCP type better suited here?

Here are the relevant parts of the RFCs:
- https://www.rfc-editor.org/rfc/rfc6544.html#section-5.2
- https://www.rfc-editor.org/rfc/rfc6544.html#appendix-B
- https://www.rfc-editor.org/rfc/rfc5389#section-7.2.2

@ashellunts Do our Passive TCP candidates only accept connections from known remote active TCP candidates? Are we checking their source IP/port when accepting the connections?

**Comment by joshua-kim** [comment]
> Hi @joshua-kim,
> server reflexive TCP candidates are not supported. Only host ones.
> Can you describe what is your use case? ...

I'm aware that for some reason it's much more difficult to support connections over TCP than over UDP (although to be honest I'm not sure why, I definitely need to research this more). Our use case is that we work on [avalanchego](https://github.com/ava-labs/avalanchego) which is a p2p blockchain network.

Currently nodes can only connect to each other assuming they're publicly discoverable + not behind a stateful firewall. Ideally, we'd like to support nodes connecting to each other via a STUN server in the case that one of them wants to sit behind a NAT.

> ... Can NAT1To1IPs help you?

My understanding is that you can pass in some hard-coded ips that will act as candidates to connect to? If this is the case I don't think this will work if two nodes behind a NAT want to connect to each other, as I think we want a publicly discoverable STUN server to mediate the connection.

**Comment by ashellunts** [comment]
If peer A is behind NAT and peer B is not, that should work.

If both peers are behind NAT, server reflexive is needed, which is not supported.

**Comment by joshua-kim** [comment]
Yeah we'd like to ideally support both peers behind a NAT! I know this feature for active tcp was only just merged in but just leaving this here as a feature request ^_^.

**Comment by ashellunts** [comment]
> @ashellunts Do our Passive TCP candidates only accept connections from known remote active TCP candidates? Are we checking their source IP/port when accepting the connections?

Agent accepts connections from any remote address and marks them as remote peer reflexive active candidate.
At the moment if an agent receives remote TCP active candidate, it ignores it, because it can't use it for initiating connections.

Though it can store it and use it for pair matching. For example to differentiate host and peer reflexive active candidates.

**Comment by ashellunts** [comment]
> Just wondering, is this even possible/reasonable to implement support for Active/Passive TCP types?
Or is the SimultaneousOpen TCP type better suited here?

@stv0g Do you mean for server reflexive type? Per standard active/passive and simultaneous-open are possible. Which one is better I don't know.

**Comment by stv0g** [comment]
> @stv0g Do you mean for server reflexive type? Per standard active/passive and simultaneous-open are possible. Which one is better I don't know.

Yes for server reflexive.. As those candidates are usually used when a NAT-box is in use which block incoming TCP connection attempts. In my understanding simultaneous open could work around that.

But thats just an assumption based on what we usually see in real-world networks. In theory there could be still 1:1 NATs, or NATs which allow incoming TCP connections. So it surely would make sense to also generate passive TCP server reflexive candidates.. I just think that they have a low likelyhood of been selected.

**Comment by ashellunts** [comment]
> Our use case is that we work on [avalanchego](https://github.com/ava-labs/avalanchego) which is a p2p blockchain network.


@joshua-kim why do you need TCP for your use case?
So you would like to connect 2 nodes with reliable connection? Have you considered webrtc datachannel? It will be reliable connection and works over UDP.

**Comment by joshua-kim** [comment]
I probably should have mentioned this earlier but we don't use webrtc at all, we have a custom networking protocol we build on top of TCP and we were just hoping to use pion/ice's ice implementation on top of it to connect nodes behind NATs.

I'm aware that pion/ice was built for pion/webrtc in mind however (although to be honest I'm not really knowledgable in webrtc at all) so I totally understand that this is really outside of the typical use case of this library.

I guess we could consider incorporating webrtc into our application based but it's definitely something I need to research more on.

**Comment by ashellunts** [comment]
I am not an expert, but I think TCP hole punching does not have high success rates.
In RFC it is written about 45% success rate, but that is data from 2005. https://datatracker.ietf.org/doc/html/rfc6544#appendix-A

**Comment by joshua-kim** [comment]
Hmm thanks for the read, had no idea that it was that bad. We're probably going to abandon this feature on our end for now unless we can migrate to something UDP based in the future.... apologies if I wasted anyone's time!
