### ISSUE TITLE
ice v2 depends on transport v2.2.2, which had a breaking change

### ISSUE THREAD

**Issue by hansgylling** [pion/ice#621]
### Your environment.
  - Version: ice v2.3.11
  - Browser: N/A
  - Other Information: N/A

The transport v2.2.2 release had a breaking which I reported here: https://github.com/pion/transport/issues/264

ice v2.3.11 specifies in its go.mod file to use transport v2.2.2, which can be seen here: https://github.com/pion/ice/blob/v2.3.11/go.mod#L13

I don't know if ice actually uses the type in transport which had the breaking change, but it feels wrong to depend on a version which had a breaking change and which was later reverted.

I think you should update the transport dependency to v2.2.4 and release a new patch release of ice v2.

**Comment by Sean-Der** [comment]
This has been fixed for a while, forgot to resolve. Thanks @hansgylling for reporting

We also added a CI job to make sure it doesn't happen again https://github.com/pion/.goassets/blob/master/ci/.github/workflows/api.yaml
