### ISSUE TITLE
build error unkown field 

### ISSUE THREAD

**Issue by runsys** [pion/ice#724]
../../../go-vgo/robotgo/window/window.h:345:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
# github.com/pion/webrtc/v2
../../../pion/webrtc/v2/icegatherer.go:88:3: unknown field Trickle in struct literal of type ice.AgentConfig
../../../pion/webrtc/v2/icegatherer.go:93:3: unknown field ConnectionTimeout in struct literal of type ice.AgentConfig
../../../pion/webrtc/v2/icegatherer.go:97:3: unknown field CandidateSelectionTimeout in struct literal of type ice.AgentConfig
../../../pion/webrtc/v2/icegatherer.go:105:30: cannot use g.api.settingEngine.vnet (variable of type *"github.com/pion/transport/vnet".Net) as transport.Net value in struct literal: *"github.com/pion/transport/vnet".Net does not implement transport.Net (wrong type for method CreateDialer)
		have CreateDialer(*net.Dialer) "github.com/pion/transport/vnet".Dialer
		want CreateDialer(*net.Dialer) transport.Dialer
../../../pion/webrtc/v2/icegatherer.go:197:15: assignment mismatch: 2 variables but g.agent.GetLocalUserCredentials returns 3 values
../../../pion/webrtc/v2/peerconnection.go:1738:16: assignment mismatch: 2 variables but sdp.NewJSEPSessionDescription returns 1 value
../../../pion/webrtc/v2/peerconnection.go:1799:16: assignment mismatch: 2 variables but sdp.NewJSEPSessionDescription returns 1 value
Error: process exited with code 1.

**Comment by Sean-Der** [comment]
@runsys What version of Go and Pion are you using?
